apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    version: v1
    app: postgres
spec:
  ports:
  - port: 5432
    protocol: "TCP"
    name: defaultpgport
    targetPort: 5432
  selector:
    app: postgres
  type: "ClusterIP"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-sts
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: bitnami/postgresql:latest
        ports:
        - containerPort: 5432
          name: postgres-port
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/postgresql/data
        env:
          - name: POSTGRESQL_USERNAME
            value: "usr123"
          - name: POSTGRESQL_PASSWORD
            value: "password123"          
          - name: POSTGRESQL_DATABASE
            value: "database"          

  volumeClaimTemplates:
  - metadata:
      name: db-storage
    spec:
      storageClassName: "standard"
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
